version: '3.4'
services:
  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    ports:
      - 8890:8890
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - db:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
  filtering:
    build: ../
    volumes:
      - ./config:/config
      - ./data/filtering:/share
    ports:
      - 8088:80
    environment:
      SERVER_PORT: "80"
      DEFAULT_APPLICATION_PROFILE_PATH: "file:/config/application-profile.ttl"
      SPARQL_ENDPOINT: "http://db:8890" # todo change that
      MAX_REQUEST_SIZE: "512MB"
      MAX_FILE_SIZE: "512MB"
      JAVA_OPTS: "-Xms512m -Xmx512m"
    restart: always
