server:
  port: ${SERVER_PORT:8089}

application-profile:
  default: ${DEFAULT_APPLICATION_PROFILE_PATH:classpath:default.shaclc}

share-folder:
  path: ${SHARE_FOLDER_DIRECTORY:${java.io.tmpdir}}

sparql:
  endpoint: ${SPARQL_ENDPOINT:http://localhost:8890}
  defaultGraphUri: ${APPLICATION_DEFAULT_GRAPH:http://mu.semte.ch/application}
  defaultBatchSize: ${DEFAULT_BATCH_SIZE:100}

spring:
  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE:512MB}
      max-file-size: ${MAX_FILE_SIZE:512MB}
logging:
  level:
    root: ${LOGGING_LEVEL:TRACE}
